services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: lomake_dev
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - AUTOMATIC_IAM_PERMISSIONS_ENABLED=true
    ports:
      - 8000:8000
    container_name: lomake_dev
  db:
    image: postgres:13.18
    container_name: lomake_db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
  adminer:
    container_name: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=lomake_db
    image: adminer:4.8.1
    ports:
      - 8080:8080 # localhost:8080/?pgsql=db&username=postgres&db=postgres&ns=public

volumes:
  pg_data:
