services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: lomake_dev
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - AUTOMATIC_IAM_PERMISSIONS_ENABLED=true
      - JAMI_URL=http://jami:3003
    ports:
      - 8000:8000
    container_name: lomake_dev
  db:
    image: postgres:13.20
    container_name: lomake_db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
  adminer:
    container_name: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=lomake_db
    image: adminer:5.2.1
    ports:
      - 8080:8080 # localhost:8080/?pgsql=db&username=postgres&db=postgres&ns=public
  jami:
    image: quay.io/toska/jami:production
    environment:
      - PORT=3003
      - NODE_ENV=dev
      - DATABASE_URL=postgres://postgres:postgres@jami-db:5432/postgres
    ports:
      - 3003:3003
    container_name: jami
  jami-db:
    image: postgres:15.8
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    container_name: jami-db
    ports:
      - 5433:5432
    volumes:
      - jami_data:/data
volumes:
  pg_data:
  jami_data:
