name: Debug in Staging

on:
  push:
    branches: [debug]

jobs:
  build:
    name: 'Build and publish staging image'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: lomake
          tags: staging ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            BASE_PATH=/tilannekuva/
            SENTRY_ENVIRONMENT=staging
          extra-args: |
            --ulimit nofile=4096:4096

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}
