name: Test feature branch

on:
  push:
    branches-ignore: 'master'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        spec:
          [
            comparison,
            degreeReform,
            form,
            formNotifications,
            happypath,
            IAMpermissions,
            management,
            misc,
            ospa,
            permissions,
            report,
            sidebar,
            yearselector,
            evaluation,
          ]
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: npm ci
        run: npm ci --no-audit --no-fund

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: seed db
        run: docker exec lomake_dev bash -c "node index.js seed"

      - name: Run cypress tests with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 6
          max_attempts: 2
          command: ./node_modules/.bin/cypress run --headless --browser chrome --spec "cypress/integration/${{ matrix.spec }}.spec.js"

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Cypress videos
          path: /home/runner/work/lomake/lomake/cypress/videos

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Cypress screenshots
          path: /home/runner/work/lomake/lomake/cypress/screenshots
