name: Build production image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: toska/lomake
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: |
            BASE_PATH=/tilannekuva/
            SENTRY_ENVIRONMENT=production
          tags: production

  report_success:
    name: 'Report release success to Tilku-channel'
    runs-on: ubuntu-latest
    needs:
    - build
    if: success()
    steps:
      - name: "Send notification to Slack"
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: deployment
          softa-url: https://opetushallinto.cs.helsinki.fi/tilannekuva
          deployment-target: production

  report_failure:
    name: 'Report release failure to Tilku-channel'
    runs-on: ubuntu-latest
    needs:
    - build
    if: failure()
    steps:
      - name: "Send notification to Slack"
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: deployment-failure